#!/bin/bash
# https://dev.to/krzysztofkaczy9/do-you-really-need-husky-247b

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

function lint_ts {
  staged_ts_files_array=$(git diff --cached --name-only --diff-filter=ACM | grep '\.ts$')
  if [ -z "$staged_ts_files_array" ]; then
    echo -e "${YELLOW}No TS files staged for commit.${NC}"
    return
  fi
  staged_ts_files_array=$(echo "$staged_ts_files_array" | sed 's|^\/||')

  # convert array to list
  staged_ts_files=""
  for file in $staged_ts_files_array; do
    staged_ts_files="$staged_ts_files $file"
  done
  staged_ts_files="${staged_ts_files# }"

  pnpm exec eslint --fix $staged_ts_files
  pnpm exec prettier --write $staged_ts_files

  linter_exit_code=$?
  if [ $linter_exit_code -ne 0 ]; then
    echo -e "${RED}X eslint found issues. Commit aborted.${NC}"
    exit 1
  fi

  # stage changes made by ESlint and Prettier
  git diff --name-only --cached --diff-filter=ACM | grep '\.ts$' | xargs git add
}

lint_go
lint_ts
echo -e "${GREEN}✔ No issues found.${NC}"
